pool:
  name: Azure Pipelines
  vmImage: windows-2019

trigger:
- master

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: true

steps:
- powershell: 'choco --version'
  displayName: 'choco --version'

- powershell: |
    $versions = $(choco search codegpt -r --all)
    if ($versions -eq $null) {
      Write-Output '##vso[task.logissue type=error;]由於 CodeGPT 尚未上架到 Chocolatey 導致 choco search codegpt -r --all 找不到版本，因此無法繼續執行！'
      # Write-Output '##vso[task.complete result=Failed;]'
      exit 1
    }
  displayName: 'choco search codegpt -r --all'

- powershell: 'choco search codegpt -r --all | C:\Windows\System32\sort.exe /r'
  displayName: 'choco search codegpt -r --all | C:\Windows\System32\sort.exe /r'

- task: PowerShell@2
  displayName: 'choco pack'
  inputs:
    targetType: filePath
    filePath: '.\build.ps1'

- powershell: 'choco install codegpt -d -s . -y --no-progress'
  displayName: 'choco install codegpt -d -s . -y --no-progress'

- powershell: 'codegpt version'
  displayName: 'codegpt version'

- powershell: 'choco uninstall codegpt -d -s . -y --no-progress'
  displayName: 'choco uninstall codegpt -d -s . -y --no-progress'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.StagingDirectory)'
  inputs:
    SourceFolder: '$(Build.Repository.LocalPath)'
    Contents: |
     codegpt.*.nupkg
     publish.ps1
     LatestChocoVersion.txt
     LatestVersion.txt
    TargetFolder: '$(Build.StagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
